/* Generated By:JavaCC: Do not edit this line. NcParserConstants.java */
package org.roiderh.syntaxhighlighter.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NcParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int START_EXPRESSION = 3;
  /** RegularExpression Id. */
  int EXPRESSION = 4;
  /** RegularExpression Id. */
  int START_PARAM_LIST = 6;
  /** RegularExpression Id. */
  int FUNCTION_CALL = 7;
  /** RegularExpression Id. */
  int LABEL = 9;
  /** RegularExpression Id. */
  int AXIS = 10;
  /** RegularExpression Id. */
  int G = 11;
  /** RegularExpression Id. */
  int M = 12;
  /** RegularExpression Id. */
  int TOOL = 13;
  /** RegularExpression Id. */
  int SPEED = 14;
  /** RegularExpression Id. */
  int LPARA = 15;
  /** RegularExpression Id. */
  int PARA = 16;
  /** RegularExpression Id. */
  int PROGNR = 17;
  /** RegularExpression Id. */
  int KEYWORD = 18;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 19;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 20;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 21;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 22;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 23;
  /** RegularExpression Id. */
  int IDENTIFIER = 24;
  /** RegularExpression Id. */
  int LETTER = 25;
  /** RegularExpression Id. */
  int PART_LETTER = 26;
  /** RegularExpression Id. */
  int ERROR = 27;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_EXPRESSION = 1;
  /** Lexical state. */
  int IN_PARAM_LIST = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "\"=\"",
    "<EXPRESSION>",
    "<token of kind 5>",
    "<START_PARAM_LIST>",
    "<FUNCTION_CALL>",
    "<token of kind 8>",
    "<LABEL>",
    "<AXIS>",
    "<G>",
    "<M>",
    "<TOOL>",
    "<SPEED>",
    "<LPARA>",
    "<PARA>",
    "<PROGNR>",
    "<KEYWORD>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<ERROR>",
  };

}
